export const routerLinks = {
  home: "/",
  search: "/search",
  aboutUs: "/about",
  photos: "/photos",
  contactUs: "/contact-us",
  createReview: "/create-review",
  createPlace: "/create-place",
  place: (slug: string) => `/places/${slug}`,
  privacyPolicy: "/privacy-policy",
  termsOfUse: "/terms-of-use",
  administrationPlaceCategories: "/administration/place-categories",
  administrationPlaceTypes: "/administration/place-types",
  personalAreaPlaces: "/personal-area/my-places",
  personalAreaReviews: "/personal-area/my-reviews",
  personalAreaSettings: "/personal-area/settings",
  personalAreaFavourites: "/personal-area/favourites",
  administrationBasePath: "/administration",
  personalAreaBasePath: "/personal-area",
};
